[package]
name = "day-04-scratchcards"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common ={ path = "../common" }
hashbrown = "0.14.3"
regex = "1.10.2"
