[package]
name = "day-05-if-you-give-a-seed-a-fertilizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
regex = "1.10.2"
thousands = "0.2.0"
